export const REQUEST_DATA = 'REQUEST_DATA'

export const LOGGED_IN = 'LOGGED_IN'
export const LOGGED_OUT = 'LOGGED_OUT'

export const REQUEST_PLACES = 'REQUEST_PLACES'
export const PLACES_FETCHED = 'PLACES_FETCHED'

export const REQUEST_SUBJECTS = 'REQUEST_SUBJECTS'
export const SUBJECTS_FETCHED = 'SUBJECTS_FETCHED'

export const REQUEST_SUBJECT = 'REQUEST_SUBJECT'
export const SUBJECT_FETCHED = 'SUBJECT_FETCHED'