export const REQUEST_DATA = 'REQUEST_DATA'

export const LOGIN = 'LOGIN'
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED'
export const LOGOUT = 'LOGOUT'

export const REQUEST_SUBJECTS = 'REQUEST_SUBJECTS'
export const SET_SUBJECTS = 'SET_SUBJECTS'

export const SET_FILTERING = 'SET_FILTERING'
export const SET_SORTING = 'SET_SORTING'
export const SET_NUMBER_PER_PAGE = 'SET_NUMBER_PER_PAGE'
export const SET_ACTIVE_PAGE = 'SET_ACTIVE_PAGE'