export const REQUEST_DATA = 'REQUEST_DATA'

export const LOGIN = 'LOGIN'
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED'
export const LOGOUT = 'LOGOUT'

export const REQUEST_SUBJECTS = 'REQUEST_SUBJECTS'
export const SET_SUBJECTS = 'SET_SUBJECTS'
export const FETCH_SUBJECTS_FAILED = 'FETCH_SUBJECTS_FAILED'

export const REQUEST_SUBJECT_PHOTO = 'REQUEST_SUBJECT_PHOTO'
export const SET_SUBJECT_PHOTO = 'SET_SUBJECT_PHOTO'

export const SET_FILTERING = 'SET_FILTERING'
export const SET_SORTING = 'SET_SORTING'